### ISSUE TITLE
Let JSON decoder be replacable

### ISSUE THREAD

**Issue by matthewoden** [spencerdcarlson/husky-elixir#4]
Ran into a conflict on install between poison 3 and poison 4. Slapping in an `override: true` made everything work again. 

Since husky is using application config anyway, could we add a key for `json_engine` that takes a decoding module? Looks like an adapter interface would just need to provide a `decode` method, which all the major JSON decoders have.

As a dep, Poison could be expanded to 3.0.0 (and later), and optional (e.g `{:poison, ">= 3.0.0", optional: true}`). Maybe even earlier than 3.0? I'd have to poke at poison's API history to be sure.

But that'd keep backwards compatibility, remove the need for overrides, and enable builds to provide their JSON parser of choice.

Example:
``` elixir
config :husky
	json_engine: Jason
    pre_commit: "mix format",
    pre_push: "mix test"
```

``` elixir
# execute.ex
def parse_json(file) do
  parser = Application.get(:husky, :json_engine, Posion)
  with {:ok, body} <- File.read(file),
       {:ok, json} <- parser.decode(body) do
    hooks = (json["husky"]["hooks"] || %{})
    Map.new(hooks,(fn {k, v} -> {String.to_atom(k), v} end)
end
```

**Comment by spencerdcarlson** [comment]
PR https://github.com/spencerdcarlson/husky-elixir/pull/10 should fix it. You'll have to version bump to `~> 1.0`
